version: '3'
services:
  app:
    container_name: front_antojitos_container
    image: front_antojitos_image
    restart: always
    build:
      context: .
      target: production
    ports:
      - '3000:80'